// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYThaOTiAoOFUeQJUceVPHQ_0VYslTII',
    appId: '1:558135539860:web:46b4df08ba3e6397309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    authDomain: 'smart-bazar-6fbdc.firebaseapp.com',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    measurementId: 'G-GBL9FNZD6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1PF9NVOJROO_y8zIE7jJmAKwri2Is1A',
    appId: '1:558135539860:android:22556da536e23aec309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERDap1wKGrfxAx2-Fl-AjXn8tBpWuU_0',
    appId: '1:558135539860:ios:24db0633147b6412309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    androidClientId: '558135539860-q74r51gr1261gdl219l1rkg0u40hhjhs.apps.googleusercontent.com',
    iosClientId: '558135539860-fna7loflh96p0svlivb8lihb1k6v4a77.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERDap1wKGrfxAx2-Fl-AjXn8tBpWuU_0',
    appId: '1:558135539860:ios:24db0633147b6412309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    androidClientId: '558135539860-q74r51gr1261gdl219l1rkg0u40hhjhs.apps.googleusercontent.com',
    iosClientId: '558135539860-fna7loflh96p0svlivb8lihb1k6v4a77.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartBazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgYThaOTiAoOFUeQJUceVPHQ_0VYslTII',
    appId: '1:558135539860:web:f0232d752dc88e26309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    authDomain: 'smart-bazar-6fbdc.firebaseapp.com',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    measurementId: 'G-NZJJEQ6JZ5',
  );

}