// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgYThaOTiAoOFUeQJUceVPHQ_0VYslTII',
    appId: '1:558135539860:web:00a40ba58073dd85309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    authDomain: 'smart-bazar-6fbdc.firebaseapp.com',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    measurementId: 'G-VFYG819ENQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF1PF9NVOJROO_y8zIE7jJmAKwri2Is1A',
    appId: '1:558135539860:android:bb6b4b130323e094309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCERDap1wKGrfxAx2-Fl-AjXn8tBpWuU_0',
    appId: '1:558135539860:ios:b7dea1e913c77588309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    androidClientId: '558135539860-q74r51gr1261gdl219l1rkg0u40hhjhs.apps.googleusercontent.com',
    iosClientId: '558135539860-02fao0epi4r4dn27vdkg41cmpd1jlem3.apps.googleusercontent.com',
    iosBundleId: 'com.app.smartBazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCERDap1wKGrfxAx2-Fl-AjXn8tBpWuU_0',
    appId: '1:558135539860:ios:b7dea1e913c77588309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    androidClientId: '558135539860-q74r51gr1261gdl219l1rkg0u40hhjhs.apps.googleusercontent.com',
    iosClientId: '558135539860-02fao0epi4r4dn27vdkg41cmpd1jlem3.apps.googleusercontent.com',
    iosBundleId: 'com.app.smartBazar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgYThaOTiAoOFUeQJUceVPHQ_0VYslTII',
    appId: '1:558135539860:web:55a44efe98dfa842309c81',
    messagingSenderId: '558135539860',
    projectId: 'smart-bazar-6fbdc',
    authDomain: 'smart-bazar-6fbdc.firebaseapp.com',
    storageBucket: 'smart-bazar-6fbdc.appspot.com',
    measurementId: 'G-QLT8EK7S04',
  );
}
